### ISSUE TITLE
need help with the project template

### ISSUE THREAD

**Issue by Akhi1** [thetechiexyz/Python4Beginners#2]
I've planned to start this Python tutorial series project and I'm determined to build it on a custom template that I built for myself from scratch. But, this is taking more time than expected as I have no prior experience in building web templates. You guys can contribute to this project and help serving the python community. 👍 

**#hacktoberfest**

**Comment by annnfrann** [comment]
Hi! I can help with this. Do you have a particular way you'd like it to look?

**Comment by Akhi1** [comment]
🔔 🔔 🔔 

Realised that developing template from scratch was a stupid idea(since I lack front-end dev skills) as it only started postponing the actual goal of the project. I'll be going forward choosing a static site generator or a bootstrap theme for this project.
