### ISSUE TITLE
toggle menubar items(not the entire menubar itself)

### ISSUE THREAD

**Issue by Akhi1** [thetechiexyz/Python4Beginners#3]
I need the sidebar to be a menubar with menu items and perform following actions
> Help 1 : Convert the sidebar menu items 'li' to toggle when the 'ul' is clicked and hide the menu items when it's clicked again ✔ DONE
> Help 2 : toggle menu should hide the content by default and display only on click.

For example : http://jsfiddle.net/dirtyd77/SLGdE/4/

**Comment by jQwotos** [comment]
I got this!
